CREATE DATABASE IF NOT EXISTS kcdb;
CREATE DATABASE IF NOT EXISTS qcdb;

CREATE USER IF NOT EXISTS 'keycloak_user'@'%' IDENTIFIED BY 'KEYCLOAK_wgZjpIxG1vGuN7am03c';
GRANT ALL PRIVILEGES ON kcdb.* TO 'keycloak_user'@'%';

CREATE USER IF NOT EXISTS 'spring_user'@'%' IDENTIFIED BY 'SPRING_wgZjpIxG1vGuN7am03c';
GRANT ALL PRIVILEGES ON qcdb.* TO 'spring_user'@'%';

FLUSH PRIVILEGES;
